[tool.poetry]
name = "ai-basics-assessment-project-24"
version = "0.1.0"
description = ""
authors = ["Kashi_Grobe <kashigrobe@icloud.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
